name: Sync Fork with Upstream

on:
  # Periodically check for new changes in the upstream repository (every hour)
  schedule:
    - cron: "*/1 * * * *"  # This runs the action every hour, you can adjust this timing as needed
  workflow_dispatch:  # Allows manual triggering via the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout your fork's code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name 'sova-tungnv'
          git config --global user.email 'nvtung@marusysvina.com'

      # Add upstream repository
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Humax-Viet-Nam/web-ai.git  # Replace with the actual upstream repository

      # Fetch changes from the upstream repository
      - name: Fetch upstream changes
        run: |
          git fetch upstream

      # Merge upstream changes into your fork's branch
      - name: Merge upstream changes
        run: |
          git checkout dual-mainpipe-main-4  # Replace with your branch if necessary
          git merge upstream/dual-mainpipe-main-4 --allow-unrelated-histories -m "Sync fork with upstream" || echo "No changes to merge"

      # Rebase and resolve conflicts (if necessary)
      - name: Rebase to resolve conflicts
        run: |
          git pull --rebase origin dual-mainpipe-main-4 || echo "No rebase required"

      # Push the changes back to your fork
      - name: Commit and push changes
        run: |
          git push --force-with-lease origin dual-mainpipe-main-4  # Replace with your branch name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
