name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch all history

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Humax-Viet-Nam/web-ai.git
          git fetch upstream

      - name: Sync changes
        run: |
          git checkout ${{ github.ref_name }}
          git merge --ff-only upstream/${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
